# 每次启动 Zsh 进程时，都会加载（读取并执行）此文件，无论是登录shell、交互式 shell，还是非交互式 shell（例如运行脚本时）。
# 由于其通用性，`.zshenv` 只应包含环境变量定义。

# Linux Homebrew
# -x 选项用于测试一个路径是否是可执行文件
if [ -x "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# 设置系统语言环境为美式英语, 字符编码为 UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# 设置终端颜色(修复远程登录主机时 kcbt 异常导致的命令预测字符无法清除的问题)
export TERM=xterm-256color

# default editor
# 决定使用 vim 作为默认的编辑器
# - nvim 太重了，而且编辑命令时，没有自动折行，导致长命令编辑体验很烂(虽然通过配置应该能自动折行，但我不想再碰 nvim 了)
# - micro VS Code/Cursor 的终端中 ctrl q 可能已经被占用，而且 micro 编辑命令不方便
export VISUAL='vim'   # 首选，大多数程序用这个
export EDITOR='vim'   # 后备，少数老程序只认这个

# $HOME/.local/bin 添加到 PATH
# 存放用户自己安装的、不属于系统级的可执行文件
# 例如当你编写了一些自己使用的脚本（例如 Python、Bash 脚本）或从源代码编译了一些程序时，可以将它们的可执行文件放在 $HOME/.local/bin 目录 # 中。这样，你可以方便地在终端中直接使用这些脚本或程序，而无需输入它们的完整路径。
export PATH="$HOME/.local/bin:$PATH"

# Rust/Cargo
. "$HOME/.cargo/env"
