# 每次启动 Zsh 进程时，都会加载（读取并执行）此文件，无论是登录shell、交互式 shell，还是非交互式 shell（例如运行脚本时）。
# 由于其通用性，`.zshenv` 只应包含环境变量定义。

# 一些不该暴露到 key, 例如 ai api key
source ~/.dotfiles/zsh/zshenv.secret

# Linux Homebrew
# -x 选项用于测试一个路径是否是可执行文件
if [ -x "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# 设置系统语言环境为美式英语, 字符编码为 UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# 设置终端颜色(修复远程登录主机时 kcbt 异常导致的命令预测字符无法清除的问题)
export TERM=xterm-256color

# default editor
export EDITOR='nvim'

# $HOME/.local/bin 添加到 PATH
# 存放用户自己安装的、不属于系统级的可执行文件
# 例如当你编写了一些自己使用的脚本（例如 Python、Bash 脚本）或从源代码编译了一些程序时，可以将它们的可执行文件放在 $HOME/.local/bin 目录 # 中。这样，你可以方便地在终端中直接使用这些脚本或程序，而无需输入它们的完整路径。
export PATH="$HOME/.local/bin:$PATH"

# Rust/Cargo
. "$HOME/.cargo/env"
