require("reload")
-- require("autoPlayClickToKeepJamoAlive")
require("HoldCmdQ")
-- require("NotiClipboard")
require("AlertClipboard")
require("FinderCopyPath")
-- require('configs.menu')
-- require("QuickLaunch")
-- require('auxiliary.getInputMethodSourceIDAndAppName')
-- require('window')
