require('reload')
-- require('configs.menu')
-- require('QuickLaunch')
require('autoPlayClickToKeepJamoAlive')
-- require('auxiliary.getInputMethodSourceIDAndAppName')
-- require('window')
-- require('HoldCmdQ')